###############################################
############## BLUEPRINTER ####################
###############################################

locale: en
debug: false
log.recipes.enable: false


############## RECIPES ############
recipes:
  - simple-cobblestone-house
  - simple-stone-house
  - simple-fortress
  - simple-gazebo
  - simple-mineshaft
  - construction-receipt
  
recipes-settings.continuous-translation: true

### SIMPLE COBLESTONE HOUSE ###
recipe.simple-cobblestone-house.name: Cobblestone House
recipe.simple-cobblestone-house.de.name: Cobblestone Haus
recipe.simple-cobblestone-house.locales:
  - de
recipe.simple-cobblestone-house.rows: 
  - FWH
  - LLL
  - CCC
recipe.simple-cobblestone-house.mats: 
  - C=COBBLESTONE
  - L=LOG
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-cobblestone-house.output: WORKBENCH


### SIMPLE STONE HAUSE ###
recipe.simple-stone-house.name: Stone House
recipe.simple-stone-house.de.name: Stein Haus
recipe.simple-stone-house.locales:
  - de
recipe.simple-stone-house.rows: 
  - FWH
  - LLL
  - SSS
recipe.simple-stone-house.mats: 
  - S=STONE
  - L=LOG
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-stone-house.output: WORKBENCH


### SIMPLE FORTRESS ###
recipe.simple-fortress.name: Fortress
recipe.simple-fortress.de.name: Festung
recipe.simple-fortress.locales:
  - de
recipe.simple-fortress.rows: 
  - FWH
  - OOO
  - OOO
recipe.simple-fortress.mats: 
  - O=OBSIDIAN
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-fortress.output: WORKBENCH
  
  
### SIMPLE GAZEBO ###
recipe.simple-gazebo.name: Gazebo
recipe.simple-gazebo.de.name: Pavillon
recipe.simple-gazebo.locales: 
  - de
recipe.simple-gazebo.rows: 
  - GGG
  - FWH
  - GGG
recipe.simple-gazebo.mats: 
  - G=STONE-1
  - A=AIR
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-gazebo.output: WORKBENCH
  
  
### SIMPLE MINE SHAFT ###
recipe.simple-mineshaft.name: Mineshaft
recipe.simple-mineshaft.de.name: Bergbauschacht
recipe.simple-mineshaft.locales: 
  - de
recipe.simple-mineshaft.rows: 
  - CBC
  - GTG
  - FWH
recipe.simple-mineshaft.mats: 
  - B=WATER_BUCKET
  - C=GLASS
  - G=GLOWSTONE
  - W=WORKBENCH
  - F=FURNACE
  - H=CHEST
  - T=TNT
recipe.simple-mineshaft.output: WORKBENCH
  
  
### CONSTRUCTION RECEIPT ###
recipe.construction-receipt.name: Construction Receipt
recipe.construction-receipt.de.name: Bauempfang
recipe.construction-receipt.locales:
  - de
recipe.construction-receipt.rows: 
  - PPP
  - PCP
  - PPP
recipe.construction-receipt.mats: 
  - P=PAPER
  - C=COBBLESTONE
recipe.construction-receipt.output: PAPER
  
  








######################################
############# LAYOUTS ###############
######################################

#############################
## RECIPES-LAYOUT MAPPINGS ##
#############################
structures.simple-cobblestone-house.layout: simple
structures.simple-cobblestone-house.mats: simple-cobblestone

structures.simple-stone-house.layout: simple
structures.simple-stone-house.mats: simple-stone
structures.simple-stone-house.require-mats-loaded: true

structures.simple-gazebo.layout: simple
structures.simple-gazebo.mats: simple-gazebo
structures.simple-gazebo.allow-replacement: true

structures.simple-mineshaft.layout: simple
structures.simple-mineshaft.mats: simple-mineshaft
structures.simple-mineshaft.allow-replacement: true
structures.simple-mineshaft.build-down: true


structures.simple-fortress.layout: simple
structures.simple-fortress.mats: simple-fortress
structures.simple-fortress.require-mats-in-bag: true

###############
## MATERIALS ##
###############
mats.simple-cobblestone.C: COBBLESTONE
mats.simple-cobblestone.L: LOG
mats.simple-cobblestone.F: FURNACE
mats.simple-cobblestone.W: WORKBENCH
mats.simple-cobblestone.H: CHEST
mats.simple-cobblestone.A: AIR
mats.simple-cobblestone.T: STONE-2
mats.simple-cobblestone.M: STONE-2
mats.simple-cobblestone.O: STONE-6

mats.simple-stone.C: STONE
mats.simple-stone.L: LOG
mats.simple-stone.F: FURNACE
mats.simple-stone.W: WORKBENCH
mats.simple-stone.H: CHEST
mats.simple-stone.A: AIR
mats.simple-stone.T: STONE
mats.simple-stone.M: STONE-2
mats.simple-stone.O: STONE-6


mats.simple-fortress.C: OBSIDIAN
mats.simple-fortress.L: OBSIDIAN
mats.simple-fortress.F: FURNACE
mats.simple-fortress.W: WORKBENCH
mats.simple-fortress.H: CHEST
mats.simple-fortress.A: AIR
mats.simple-fortress.T: OBSIDIAN
mats.simple-fortress.M: OBSIDIAN
mats.simple-fortress.O: OBSIDIAN

mats.simple-gazebo.C: STONE-2
mats.simple-gazebo.L: BLUEPRINTER_SKIP
mats.simple-gazebo.F: FURNACE
mats.simple-gazebo.W: WORKBENCH
mats.simple-gazebo.H: CHEST
mats.simple-gazebo.A: BLUEPRINTER_SKIP
mats.simple-gazebo.T: GLASS
mats.simple-gazebo.M: STONE-4
mats.simple-gazebo.O: STONE-6

mats.simple-mineshaft.C: GLASS
mats.simple-mineshaft.L: GLASS
mats.simple-mineshaft.F: FURNACE
mats.simple-mineshaft.W: WORKBENCH
mats.simple-mineshaft.H: CHEST
mats.simple-mineshaft.A: AIR
mats.simple-mineshaft.T: GLASS
mats.simple-mineshaft.M: GLOWSTONE
mats.simple-mineshaft.O: WATER

########################
## SYMBOLS AND FLOORS ##
########################

##SIMPLE LAYOUT
layouts.simple.symbols: 
  - C
  - L
  - F
  - W
  - H
  - A
  - T
  - M
  - O
  
layouts.simple.layers: 
  - L1
  - L2
  - L3
  - L4
  - L4
  - L4
  - L1
  
layouts.simple.layer.L1.rows: 
  - R1
  - R2
  - R3
  - R4
  - R3
  - R2
  - R1
layouts.simple.layer.L1.row.R1: CTCCCTC
layouts.simple.layer.L1.row.R2: TCCCCCT
layouts.simple.layer.L1.row.R3: CCMMMCC
layouts.simple.layer.L1.row.R4: CCMOMCC

layouts.simple.layer.L2.rows: 
  - R1
  - R2
  - R3
  - R3
  - R3
  - R4
  - R5
layouts.simple.layer.L2.row.R1: CTLALTC
layouts.simple.layer.L2.row.R2: TAAAAAT
layouts.simple.layer.L2.row.R3: LAAAAAL
layouts.simple.layer.L2.row.R4: TAHWFAT
layouts.simple.layer.L2.row.R5: CTLLLTC

layouts.simple.layer.L3.rows: 
  - R1
  - R2
  - R3
  - R4
  - R3
  - R2
  - R5
layouts.simple.layer.L3.row.R1: CTLALTC
layouts.simple.layer.L3.row.R2: TAAAAAT
layouts.simple.layer.L3.row.R3: LAAAAAL
layouts.simple.layer.L3.row.R4: AAAAAAA
layouts.simple.layer.L3.row.R5: CTLALTC

layouts.simple.layer.L4.rows: 
  - R1
  - R2
  - R3
  - R3
  - R3
  - R2
  - R1
layouts.simple.layer.L4.row.R1: CTLLLTC
layouts.simple.layer.L4.row.R2: TAAAAAT
layouts.simple.layer.L4.row.R3: LAAAAAL

##ADD SYMBOLS AND FLOORS FOR YOUR NEW LAYOUT BELOW









messages.block-typer-loading-recipes.en: Loading recipes
messages.blueprinter-required-materials.en: Required Materials
messages.blueprinter-improper-orientation.en: §4You must place this item directly in front of you.
messages.blueprinter-missing-required-materials.en: §4You are missing required materials for construction.
messages.blueprinter-right-click-to-view-requirements.en: §2Right click the item to see what is needed.
messages.blueprinter-undefined-material.en: §4Material undefined - {0}
messages.blueprinter-non-air-or-stationary-water-block-detected.en: §4A block which was not air or stationary water was in the way of construction - {0}
messages.blueprinter-undefined-block-detected.en: §4An undefined block was encountered during construction - {0}
messages.blueprinter-construction-receipt.en: Construction Receipt
messages.blueprinter-material-swap.en: Click a block in your inventory to pick a new material for symbol group [{0}]
messages.blueprinter-return.en: Return
messages.blueprinter-teleport.en: Teleport
messages.blueprinter-hide.en: Hide
messages.blueprinter-show.en: Show
messages.blueprinter-missing-world.en: Missing world {0}
messages.blueprinter-missing-world.en: Missing world {0}
messages.blueprinter-require-mats-in-bag.en: Requires materials in bag
messages.blueprinter-require-mats-loaded.en: Requires loaded materials
messages.blueprinter-build-down.en: Builds down
messages.blueprinter-allow-replacement.en: Replaces blocks
messages.blueprinter-height.en: Height


messages.block-typer-loading-recipes.de: Laden Rezepte
messages.blueprinter-required-materials.de: §4Benötigtes Material
messages.blueprinter-improper-orientation.de: §4Du must diese Position direkt vor dir platzieren.
messages.blueprinter-missing-required-materials.de: §4Du fehlst benötigte Materialien für den Bau.
messages.blueprinter-right-click-to-view-requirements.de: §2Klicke mit der rechten Maustaste auf das Element, um zu sehen, was benötigt wird.
messages.blueprinter-undefined-material.de: §4Material undefiniert - {0}
messages.blueprinter-non-air-or-stationary-water-block-detected.de: §4Ein Block, der weder Luft noch stationäres Wasser war, war im Aufbau - {0}
messages.blueprinter-undefined-block-detected.de: §4Ein unbestimmter Block wurde während der Konstruktion angetroffen - {0}
messages.blueprinter-construction-receipt.de: Bauempfang
messages.blueprinter-material-swap.de: Klicke auf einen Block in deinem Inventar, um ein neues Material für die Symbolgruppe [{0}]
messages.blueprinter-return.de: Geh zurück
messages.blueprinter-teleport.de: Teleport
messages.blueprinter-hide.de: Gebäude ausblenden
messages.blueprinter-show.de: Gebäude anzeigen
messages.blueprinter-missing-world.de: Fehlende Welt {0}
blueprinter-require-mats-in-bag.de: Benötigt Material im Beutel
messages.blueprinter-require-mats-loaded.de: Erfordert, dass Materialien geladen werden.
messages.blueprinter-build-down.de: Baut nach unten
messages.blueprinter-allow-replacement.de: Ersetzt Blöcke
messages.blueprinter-height.de: Höhe



  
  
  
  
  
  