###############################################
############## EXAMPLE ########################
###############################################



############## DEBUG ##########################
locale: en
debug: true
log.recipes.enable: true


############## RECIPES ############
recipes:
  - starter-house


###############################################
#################### ITEMS ####################
###############################################


################## BEGIN Starter House ############
recipe.starter-house.name: Starter House
recipe.starter-house.rows: 
  - FWH
  - LLL
  - CCC
recipe.starter-house.mats: 
  - C=STONE
  - L=LOG
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.starter-house.output: WORKBENCH


layout.starter-house.mats.symbols: 
  - C
  - L
  - F
  - W
  - H
  - A
layout.starter-house.mats.definitions.C: COBBLESTONE
layout.starter-house.mats.definitions.L: LOG
layout.starter-house.mats.definitions.F: FURNACE
layout.starter-house.mats.definitions.W: WORKBENCH
layout.starter-house.mats.definitions.H: CHEST
layout.starter-house.mats.definitions.A: AIR
layout.starter-house.floors: 
  - F1
  - F2
  - F3
  - F4
  - F1
layout.starter-house.floor.F1.rows: 
  - R1
  - R1
  - R1
  - R1
  - R1
  - R1
  - R1
layout.starter-house.floor.F1.row.R1: CCCCCCC

layout.starter-house.floor.F2.rows: 
  - R1
  - R2
  - R2
  - R2
  - R2
  - R3
  - R4
layout.starter-house.floor.F2.row.R1: LLLALLL
layout.starter-house.floor.F2.row.R2: LAAAAAL
layout.starter-house.floor.F2.row.R3: LAHWFAL
layout.starter-house.floor.F2.row.R4: LLLLLLL

layout.starter-house.floor.F3.rows: 
  - R1
  - R2
  - R2
  - R3
  - R2
  - R2
  - R4
layout.starter-house.floor.F3.row.R1: LLLALLL
layout.starter-house.floor.F3.row.R2: LAAAAAL
layout.starter-house.floor.F3.row.R3: AAAAAAA
layout.starter-house.floor.F3.row.R4: LLLALLL

layout.starter-house.floor.F4.rows: 
  - R1
  - R2
  - R2
  - R2
  - R2
  - R2
  - R1
layout.starter-house.floor.F4.row.R1: LLLLLLL
layout.starter-house.floor.F4.row.R2: LAAAAAL

















  
  
  
  
  
  