###############################################
############## BLUEPRINTER ####################
###############################################

locale: en
debug: false
log.recipes.enable: false


############## RECIPES ############
recipes:
  - simple-cobblestone-house
  - simple-stone-house
  - simple-fortress
  - simple-gazebo
  - simple-bunker
  - construction-receipt
  
recipes-settings.continuous-translation: true

### SIMPLE COBLESTONE HOUSE ###
recipe.simple-cobblestone-house.name: Cobblestone House
recipe.simple-cobblestone-house.de.name: Cobblestone Haus
recipe.simple-cobblestone-house.locales:
  - de
recipe.simple-cobblestone-house.rows: 
  - FWH
  - LLL
  - CCC
recipe.simple-cobblestone-house.mats: 
  - C=COBBLESTONE
  - L=LOG
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-cobblestone-house.output: WORKBENCH


### SIMPLE STONE HAUSE ###
recipe.simple-stone-house.name: Stone House
recipe.simple-stone-house.de.name: Stein Haus
recipe.simple-stone-house.locales:
  - de
recipe.simple-stone-house.rows: 
  - FWH
  - LLL
  - SSS
recipe.simple-stone-house.mats: 
  - S=STONE
  - L=LOG
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-stone-house.output: WORKBENCH
recipe.simple-stone-house.lore:
  - Requires Materials to be 
  - loaded before placing.
recipe.simple-stone-house.de.lore:
  - Dieses Gebäude erfordert, 
  - dass die Materialien zuerst 
  - geladen werden.


### SIMPLE FORTRESS ###
recipe.simple-fortress.name: Fortress
recipe.simple-fortress.de.name: Festung
recipe.simple-fortress.locales:
  - de
recipe.simple-fortress.rows: 
  - FWH
  - OOO
  - OOO
recipe.simple-fortress.mats: 
  - O=OBSIDIAN
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-fortress.output: WORKBENCH
recipe.simple-fortress.lore:
  - This building spends the required 
  - materials from your bag.
recipe.simple-fortress.de.lore:
  - Dieses Gebäude verbringt die 
  - benätigten Materialien 
  - aus deine Tasche.
  
  
### SIMPLE GAZEBO ###
recipe.simple-gazebo.name: Gazebo
recipe.simple-gazebo.de.name: Pavillon
recipe.simple-gazebo.locales: 
  - de
recipe.simple-gazebo.rows: 
  - GGG
  - FWH
  - GGG
recipe.simple-gazebo.mats: 
  - G=STONE-1
  - A=AIR
  - F=FURNACE
  - W=WORKBENCH
  - H=CHEST
recipe.simple-gazebo.output: WORKBENCH
recipe.simple-gazebo.lore: 
  - Avoids replacing blocks 
  - when possible.
recipe.simple-gazebo.de.lore: 
  - Vermeidet das Ersetzen von 
  - Blöcken, wenn möglich.
  
  
### SIMPLE BUNKER ###
recipe.simple-bunker.name: Bunker
recipe.simple-bunker.de.name: Bunker
recipe.simple-bunker.locales: 
  - de
recipe.simple-bunker.rows: 
  - CCC
  - DTD
  - GWG
recipe.simple-bunker.mats: 
  - C=COBBLESTONE
  - G=GLOWSTONE
  - W=WORKBENCH
  - D=DIRT
  - T=TNT
recipe.simple-bunker.output: WORKBENCH
recipe.simple-bunker.lore: 
  - Built downwards.
  - Blocks will be replaced
recipe.simple-bunker.de.lore: 
  - Nach unten gebaut.
  - Blöcke werden ersetzt.
  
  
### CONSTRUCTION RECEIPT ###
recipe.construction-receipt.name: Construction Receipt
recipe.construction-receipt.de.name: Bauempfang
recipe.construction-receipt.locales:
  - de
recipe.construction-receipt.rows: 
  - PPP
  - PCP
  - PPP
recipe.construction-receipt.mats: 
  - P=PAPER
  - C=COBBLESTONE
recipe.construction-receipt.output: PAPER
  
  








######################################
############# LAYOUTS ###############
######################################

#############################
## RECIPES-LAYOUT MAPPINGS ##
#############################
structures.simple-cobblestone-house.layout: simple
structures.simple-cobblestone-house.mats: simple-cobblestone

structures.simple-stone-house.layout: simple
structures.simple-stone-house.mats: simple-stone
structures.simple-stone-house.require-mats-loaded: true

structures.simple-gazebo.layout: simple
structures.simple-gazebo.mats: simple-gazebo
structures.simple-gazebo.allow-replacement: true

structures.simple-bunker.layout: simple
structures.simple-bunker.mats: simple-bunker
structures.simple-bunker.allow-replacement: true
structures.simple-bunker.build-down: true


structures.simple-fortress.layout: simple
structures.simple-fortress.mats: simple-fortress
structures.simple-fortress.require-mats-in-bag: true

###############
## MATERIALS ##
###############
mats.simple-cobblestone.C: COBBLESTONE
mats.simple-cobblestone.L: LOG
mats.simple-cobblestone.F: FURNACE
mats.simple-cobblestone.W: WORKBENCH
mats.simple-cobblestone.H: CHEST
mats.simple-cobblestone.A: AIR

mats.simple-stone.C: STONE
mats.simple-stone.L: LOG
mats.simple-stone.F: FURNACE
mats.simple-stone.W: WORKBENCH
mats.simple-stone.H: CHEST
mats.simple-stone.A: AIR

mats.simple-fortress.C: OBSIDIAN
mats.simple-fortress.L: OBSIDIAN
mats.simple-fortress.F: FURNACE
mats.simple-fortress.W: WORKBENCH
mats.simple-fortress.H: CHEST
mats.simple-fortress.A: AIR

mats.simple-gazebo.C: STONE-1
mats.simple-gazebo.L: BLUEPRINTER_SKIP
mats.simple-gazebo.F: FURNACE
mats.simple-gazebo.W: WORKBENCH
mats.simple-gazebo.H: CHEST
mats.simple-gazebo.A: BLUEPRINTER_SKIP

mats.simple-bunker.C: COBBLESTONE
mats.simple-bunker.L: DIRT
mats.simple-bunker.F: GLOWSTONE
mats.simple-bunker.W: WORKBENCH
mats.simple-bunker.H: GLOWSTONE
mats.simple-bunker.A: AIR

########################
## SYMBOLS AND FLOORS ##
########################

##SIMPLE LAYOUT
layouts.simple.symbols: 
  - C
  - L
  - F
  - W
  - H
  - A
  
layouts.simple.layers: 
  - L1
  - L2
  - L3
  - L4
  - L4
  - L4
  - L1
  
layouts.simple.layer.L1.rows: 
  - R1
  - R1
  - R1
  - R1
  - R1
  - R1
  - R1
layouts.simple.layer.L1.row.R1: CCCCCCC

layouts.simple.layer.L2.rows: 
  - R1
  - R2
  - R2
  - R2
  - R2
  - R3
  - R4
layouts.simple.layer.L2.row.R1: CLLALLC
layouts.simple.layer.L2.row.R2: LAAAAAL
layouts.simple.layer.L2.row.R3: LAHWFAL
layouts.simple.layer.L2.row.R4: CLLLLLC

layouts.simple.layer.L3.rows: 
  - R1
  - R2
  - R2
  - R3
  - R2
  - R2
  - R4
layouts.simple.layer.L3.row.R1: CLLALLC
layouts.simple.layer.L3.row.R2: LAAAAAL
layouts.simple.layer.L3.row.R3: AAAAAAA
layouts.simple.layer.L3.row.R4: CLLALLC

layouts.simple.layer.L4.rows: 
  - R1
  - R2
  - R2
  - R2
  - R2
  - R2
  - R1
layouts.simple.layer.L4.row.R1: CLLLLLC
layouts.simple.layer.L4.row.R2: LAAAAAL

##ADD SYMBOLS AND FLOORS FOR YOUR NEW LAYOUT BELOW









messages.block-typer-loading-recipes.en: Loading recipes
messages.blueprinter-required-materials.en: Required Materials
messages.blueprinter-improper-orientation.en: §4You must place this item directly in front of you.
messages.blueprinter-missing-required-materials.en: §4You are missing required materials for construction.
messages.blueprinter-right-click-to-view-requirements.en: §2Right click the item to see what is needed.
messages.blueprinter-undefined-material.en: §4Material undefined - {0}
messages.blueprinter-non-air-or-stationary-water-block-detected.en: §4A block which was not air or stationary water was in the way of construction - {0}
messages.blueprinter-undefined-block-detected.en: §4An undefined block was encountered during construction - {0}
messages.blueprinter-construction-receipt.en: Construction Receipt
messages.blueprinter-material-swap.en: Click a block in your inventory to pick a new material for symbol group [{0}]
messages.blueprinter-return.en: Return
messages.blueprinter-teleport.en: Teleport
messages.blueprinter-hide.en: Hide
messages.blueprinter-show.en: Show
messages.blueprinter-missing-world.en: Missing world {0}


messages.block-typer-loading-recipes.de: Laden Rezepte
messages.blueprinter-required-materials.de: §4Benötigtes Material
messages.blueprinter-improper-orientation.de: §4Du must diese Position direkt vor dir platzieren.
messages.blueprinter-missing-required-materials.de: §4Du fehlst benötigte Materialien für den Bau.
messages.blueprinter-right-click-to-view-requirements.de: §2Klicke mit der rechten Maustaste auf das Element, um zu sehen, was benötigt wird.
messages.blueprinter-undefined-material.de: §4Material undefiniert - {0}
messages.blueprinter-non-air-or-stationary-water-block-detected.de: §4Ein Block, der weder Luft noch stationäres Wasser war, war im Aufbau - {0}
messages.blueprinter-undefined-block-detected.de: §4Ein unbestimmter Block wurde während der Konstruktion angetroffen - {0}
messages.blueprinter-construction-receipt.de: Bauempfang
messages.blueprinter-material-swap.de: Klicke auf einen Block in deinem Inventar, um ein neues Material für die Symbolgruppe [{0}]
messages.blueprinter-return.de: Geh zurück
messages.blueprinter-teleport.de: Teleport
messages.blueprinter-hide.de: Gebäude ausblenden
messages.blueprinter-show.de: Gebäude anzeigen
messages.blueprinter-missing-world.de: Fehlende Welt {0}



  
  
  
  
  
  