name: Blueprinter
version: 1.0.0
main:  com.blocktyper.blueprinter.BlueprinterPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Design structures.  Craft items which will build them out.